# PyTorch Fundamentals Exercises
Notebook completed by Adam Lang as part of ZTM/Udem PyTorch for Deep Learning Bootcamp
1. Documentation reading
A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

The documentation on `torch.tensor`.
The documentation on `torch.cuda`.

In [1]:
import torch

# 2. Create a random tensor with shape (7, 7).

In [2]:
#random tensor 7,7
random_tensor = torch.rand(7,7)
random_tensor

tensor([[0.3880, 0.4692, 0.1339, 0.5970, 0.8394, 0.8861, 0.3271],
        [0.7915, 0.2872, 0.9372, 0.4465, 0.1998, 0.2791, 0.3683],
        [0.4120, 0.7327, 0.5935, 0.2877, 0.4884, 0.2759, 0.4139],
        [0.7673, 0.4989, 0.4727, 0.3140, 0.6270, 0.9692, 0.0668],
        [0.5706, 0.2123, 0.0123, 0.4243, 0.7503, 0.0277, 0.8385],
        [0.3914, 0.5682, 0.9001, 0.0685, 0.0646, 0.2717, 0.9260],
        [0.0088, 0.0549, 0.3059, 0.8009, 0.1209, 0.2592, 0.1805]])

In [4]:
#check shape of random_tensor and ndim
print(f"Shape of random tensor is: {random_tensor.shape}")
print(f"Dimensions of random tensor are: {random_tensor.ndim}")

Shape of random tensor is: torch.Size([7, 7])
Dimensions of random tensor are: 2


# 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [5]:
#check shape of random tensor
random_tensor.shape

torch.Size([7, 7])

In [6]:
#create another random tensor of shape (1,7)
random_tensor2 = torch.rand(1,7)
random_tensor2

tensor([[0.3403, 0.1731, 0.6220, 0.4826, 0.9745, 0.3627, 0.2511]])

In [7]:
#check shape and ndim of random_tensor2
print(f"Shape of random tensor2: {random_tensor2.shape}")
print(f"Dims of random tensor2: {random_tensor2.ndim}")

Shape of random tensor2: torch.Size([1, 7])
Dims of random tensor2: 2


summary: So we have 2 tensors one with shape of `7,7` and other `1,7`.

* The inner dimensions DO NOT match so matrix multiplication will not work.
* We will have to transform a tensor to perform matrix multiplication.

In [8]:
# transform random_tensor2
random_tensor2 = random_tensor2.T


#print result
print(random_tensor2)
print(random_tensor2.shape)

tensor([[0.3403],
        [0.1731],
        [0.6220],
        [0.4826],
        [0.9745],
        [0.3627],
        [0.2511]])
torch.Size([7, 1])


summary: Now we have tensors of shape `7,7` and `7,1`
- inner dimensions match so we can perform matmul

In [9]:
#matrix multiplication
torch.matmul(random_tensor, random_tensor2)

tensor([[1.8061],
        [1.5058],
        [1.4550],
        [1.7723],
        [1.3951],
        [1.2185],
        [0.8464]])

# 4. Set the random seed to 0 and do 2 & 3 over again.

The output should be:

`(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))`

In [31]:
# Step 1: set random seed to 0 and create random tensor again
#SET RANDOM_SEED
RANDOM_SEED = 0
#use manual_seed function
torch.manual_seed(RANDOM_SEED)
x = torch.rand(size=(7,7))
y = torch.rand(size=(1,7))

#print random_tensor again
print(x)
print(f"Shape of random_tensor x is: {x.shape}")
print(y)
print(f"Shape of random_tensor y is: {y.shape}")

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
Shape of random_tensor x is: torch.Size([7, 7])
tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])
Shape of random_tensor y is: torch.Size([1, 7])


In [34]:
#multiply again
print(torch.mm(x, y.T))
print(torch.mm(x,y.T).shape)


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])
torch.Size([7, 1])


# 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)
If there is, set the GPU random seed to 1234.

In [35]:
# set cuda to 1234
torch.cuda.manual_seed(1234)

# 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:


`Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))`

In [39]:
# check if cuda is available
device = "cuda" if torch.cuda.is_available() else "cpu"

device = print(f"Device: {device}")

Device: cpu


In [42]:
#create 2 random tensors
# set random seed
RANDOM_SEED = 1234
torch.manual_seed(RANDOM_SEED)

# create 2 random tensors
rand_tensor = torch.rand(size=(2,3)).to(device)
rand_tensor2 = torch.rand(size=(2,3)).to(device)


#print results
print(rand_tensor, rand_tensor2)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]) tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])


# 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
The output should look like:

`(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))`

In [43]:
#print shapes of tensors from #6 above
print(f"Shape of rand_tensor is: {rand_tensor.shape}")
print(f"Shape of rand_tensor2 is: {rand_tensor2.shape}")

Shape of rand_tensor is: torch.Size([2, 3])
Shape of rand_tensor2 is: torch.Size([2, 3])


In [45]:
# perform matrix multiplication
mm_tensor = torch.matmul(rand_tensor, rand_tensor2.T)

mm_tensor

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

# 8. Find the maximum and minimum values of the output of 7.

In [46]:
# max values
print(f"Max of rand_tensor: {rand_tensor.max()}")
print(f"Max of rand_tensor2: {rand_tensor2.max()}")
print(f"Max of mm_tensor: {mm_tensor.max()}")

Max of rand_tensor: 0.7006447315216064
Max of rand_tensor2: 0.7837080359458923
Max of mm_tensor: 0.5617256760597229


In [47]:
# min values
print(f"Min of rand_tensor: {rand_tensor.min()}")
print(f"Min of rand_tensor: {rand_tensor2.min()}")
print(f"Min of mm_tensor: {mm_tensor.min()}")

Min of rand_tensor: 0.028979241847991943
Min of rand_tensor: 0.05179738998413086
Min of mm_tensor: 0.3647301495075226


# 9. Find the maximum and minimum index values of the output of 7.

In [48]:
# maximum indexes
print(f"Min of rand_tensor: {rand_tensor.argmax()}")
print(f"Min of rand_tensor: {rand_tensor2.argmax()}")
print(f"Min of mm_tensor: {mm_tensor.argmax()}")

Min of rand_tensor: 5
Min of rand_tensor: 4
Min of mm_tensor: 3


In [49]:
# min indexes
print(f"Min of rand_tensor: {rand_tensor.argmin()}")
print(f"Min of rand_tensor: {rand_tensor2.argmin()}")
print(f"Min of mm_tensor: {mm_tensor.argmin()}")

Min of rand_tensor: 0
Min of rand_tensor: 0
Min of mm_tensor: 0


# 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
The output should look like:

`tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])`

In [55]:
# make random tensor shape (1,1,1,10)
# set seed to 7
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)
# create random tensor
tensor_A = torch.rand(size=(1,1,1,10))
tensor_A

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])

In [56]:
# create new tensor from other tensor and squeeze tensor removes all dimensions of size '1'
torch.manual_seed(RANDOM_SEED)
tensor_B = torch.squeeze(tensor_A)
tensor_B

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])

In [57]:
# get shapes of both tensors: tensor_A, tensor_B
print(f"Shape of tensor_A is: {tensor_A.shape}")
print(f"Shape of tensor_B is: {tensor_B.shape}")

Shape of tensor_A is: torch.Size([1, 1, 1, 10])
Shape of tensor_B is: torch.Size([10])
